name: Synchronization

env:
  WORKFLOW_BRANCH: feat/synchronization-workflow

on:
  pull_request:
  # TODO uncomment
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    # uses: atls/shared/.github/workflows/synchronization.yaml@master
    uses: atls/shared/.github/workflows/synchronization.yaml@${{ env.WORKFLOW_BRANCH }}
    permissions: write-all
    with:
      appId: ${{ vars.REES46_PUBLISHER_ID }}
      targetRepository: rees46/kmp
      syncIgnore: ".git,.idea,.github"
      replacementExtentions: "*.kts,*.kt"
      replacementContents: "atls|rees46"
    secrets:
      privateKey: ${{ secrets.REES46_PUBLISHER_SECRET }}
