# { "branches": ["master"], "plugins": [
{
  "branches": ["refactor/version"],
  "plugins":
    [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/git",
        {
          "assets": ["version.properties"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        },
      ],
      ["@semantic-release/github", { "pullRequests": true }],
      [
        "@semantic-release/exec",
        {
          "prepare": "./gradlew updateVersion -PnewVersion=${nextRelease.version}",
        },
      ],
    ],
}
