# { "branches": ["master"], "plugins": [
{ "branches": ["refactor/version"], "plugins": [
      # "@semantic-release/commit-analyzer",
      # "@semantic-release/release-notes-generator",
      [
        "@semantic-release/exec",
        { "prepare": "./gradlew bumpPatchVersion --no-configuration-cache" },
      ],
    ] }
