name: Reusable publish action
description: Reusable publish action

inputs:
  appId:
    required: true
    description: "App ID for committing and pushing"
  appSecret:
    description: "App secret"
    required: true
  githubToken:
    description: "github token"
    required: true

runs:
  using: composite

  steps:
    - name: debug
      shell: bash
      run: |
        echo "wofklow triggered"

    # - name: Checkout
    #   uses: actions/checkout@v4
    #   with:
    #     token: ${{ steps.app-token.outputs.token }}
    #     ref: master
    #     fetch-depth: 0
    #
    # - name: publish
    #   shell: bash
    #   env:
    #     GITHUB_TOKEN: ${{ inputs.githubToken }}
    #     GITHUB_USER: ${{ github.repository_owner }}
    #     GITHUB_REPO: ${{ github.repository }}
    #   run: |
    #     ./gradlew :ios:publishAllPublicationsToGitHubPackagesRepository
    #     ./gradlew :android:publishAllPublicationsToGitHubPackagesRepository
    #     ./gradlew :compose:publishAllPublicationsToGitHubPackagesRepository
    #     ./gradlew :multiplatform:publishAllPublicationsToGitHubPackagesRepository
