name: Publish workflow

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: "App ID for committing and pushing"
    secrets:
      appSecret:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ inputs.secrets }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          ./gradlew publishMultiplatformPublicationToGitHubPackagesRepository
