name: Reusable Android SDK version

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: "App ID for committing and pushing"
    secrets:
      appSecret:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      committed: ${{ steps.committer.outputs.committed }}

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: master

      - name: Bump version
        env:
          FILE_PATH: ${{ inputs.podSpecFilePath }}
        id: version
        run: |
          current_version=$(awk -F"'" '/s.version *=/ {print $2}' "$FILE_PATH")
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i "s/$current_version/$new_version/" "$FILE_PATH"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Retrieve version
        id: versionName
        env:
          FILE_PATH: ./personalization-sdk/build.gradle
        run: |
          version=$(grep -o "version='[^']*'" $FILE_PATH | head -1 | cut -d"'" -f2)
          echo "versionName=$version" >> $GITHUB_ENV
          echo "versionName=$version" >> $GITHUB_OUTPUT

      - name: Commit changes
        id: committer
        uses: planetscale/ghcommit-action@v0.1.44
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          repo: ${{ github.repository }}
          branch: master
          commit_message: "chore(common): version bump to ${{ steps.versionName.outputs.versionName }}"
          file_pattern: "personalization-sdk"
