name: Patch version, publish to GitHubPackages and create new GitHub release

on:
  pull_request:
  # TODO uncomment
  #   types:
  #     - closed
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      # TODO uncomment
      # - uses: atls/kmp/.github/actions/version@master
      #   if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
      - uses: atls/kmp/.github/actions/version@refactor/version
        with:
          appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

  # TODO uncomment
  # publish:
  #   needs: version
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: atls/kmp/.github/actions/publish@master
  #       with:
  #         appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
  #         appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
  #         githubToken: ${{ secrets.GITHUB_TOKEN }}
  #
  # release:
  #   needs: [publish, version]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: atls/kmp/.github/actions/release@master
  #       with:
  #         appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
  #         appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
