name: Patch version, publish to GitHubPackages and create new GitHub release

on:
  pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  # version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: atls/kmp/.github/actions/version@fix/workflow
  #       if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
  #       with:
  #         appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
  #         appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: atls/kmp/.github/actions/publish@fix/workflow
        with:
          appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [publish, version]
    runs-on: ubuntu-latest
    steps:
      - uses: atls/kmp/.github/actions/release@fix/workflow
        with:
          appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
