name: Publish

on:
  pull_request:
    # TODO uncomment
    # types:
    #   - closed
    branches:
      - "release/**"
  workflow_dispatch:

jobs:
  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: atls/kmp/.github/actions/publish@release/debug-release-branch
        # TODO uncomment
        # - uses: atls/kmp/.github/actions/publish@master
        #   if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        with:
          appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
