name: Patch version, publish to GitHubPackages and create new GitHub release

on:
  pull_request:
  # TODO uncomment
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  # version:
  # TODO uncomment
  # if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
  # uses: atls/kmp/.github/reusable-workflows/android-version.yml@master
  # uses: atls/kmp/.github/reusable-workflows/android-version.yml@feat/publish-workflow
  # permissions: write-all
  # with:
  #   appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
  # secrets:
  #   appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          private-key: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          ./gradlew publish

  # publish:
  #   # TODO uncomment
  #   # needs: version
  #   # uses: atls/kmp/.github/reusable-workflows/version.yml@master
  #   uses: atls/kmp/.github/reusable-workflows/version.yml@feat/publish-workflow
  #   permissions: write-all
  #   with:
  #     appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
  #     PROPERTIES_FILE: gradle.properties
  #     SIGNING_SECRET_KEY_RING_FILE: com.rees46.key.gpg
  #     SIGNING_SECRET_KEY_RING_FILE_LOCATION: ./personalization-sdk
  #     OSSRH_USERNAME: ${{ vars.OSSRH_USERNAME }}
  #     VARIANT_NAME: ${{ vars.REES_VARIANT_NAME }}
  #     URL: ${{ vars.REES_REPO_URL }}
  #     MAVEN_REPOSITORY_URL: ${{ vars.REES_MAVEN_URL }}
  #     GRADLE_VERSION: 8.8
  #   secrets:
  #     SONATA_STAGING_PROFILE_ID: ${{ secrets.SONATA_STAGING_PROFILE_ID }}
  #     appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
  #     SONATA_USERNAME: ${{ secrets.SONATA_USERNAME }}
  #     SONATA_PASSWORD: ${{ secrets.SONATA_PASSWORD }}
  #     OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  #     SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  #     SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  #     SIGNING_KEY_FILE_AS_BASE64_STRING: ${{ secrets.SIGNING_KEY_FILE_AS_BASE64_STRING }}
  #
  # release:
  #   # TODO uncomment
  #   # needs: [publish, version]
  #   # uses: atls/kmp/.github/reusable-workflows/release.yml@master
  #   permissions: write-all
  #   with:
  #     appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
  #   secrets:
  #     appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
