name: Patch version, publish to GitHubPackages and create new GitHub release

on:
  pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  version:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: atls/kmp/.github/actions/version/action.yml@master
    permissions: write-all
    with:
      appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
    secrets:
      appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

  publish:
    needs: version
    uses: atls/kmp/.github/actions/publish/action.yml@master
    permissions: write-all
    with:
      appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
    secrets:
      appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

  release:
    needs: [publish, version]
    uses: atls/kmp/.github/actions/release/action.yml@master
    permissions: write-all
    with:
      appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
    secrets:
      appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
