name: Synchronization

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: atls/shared/.github/workflows/synchronization.yaml@master
    permissions: write-all
    with:
      appId: ${{ vars.REES46_PUBLISHER_ID }}
      targetRepository: rees46/kmp
      targetOrganization: rees46
      syncIgnore: ".git,.idea,.github/workflows/synchronization.yml,.github/ISSUE_TEMPLATE"
      replacementExtentions: "*.kts,*.kt,*.yml,*.yaml"
      replacementContents: "ATLANTIS_SUPER_BOT_APP_I|PUBLIVERSIONER_ID,ATLANTIS_SUPER_BOT_PRIVATE_KEY|PUBLIVERSIONER_SECRET,atls|rees46"
      sourceDirname: atls
      targetDirname: rees46
    secrets:
      privateKey: ${{ secrets.REES46_PUBLISHER_SECRET }}
