name: Bump version

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  find-release-commit:
    # TODO uncomment
    # uses: atls/shared/.github/workflows/release-commit-finder.yaml@master
    uses: atls/shared/.github/workflows/release-commit-finder.yaml@refactor/workflow
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  bump-version:
    needs: find-release-commit
    if: |
      github.event_name == 'workflow_dispatch' || (
        github.event_name == 'push' &&
        needs.find-release-commit.outputs.hasCommit == 'false')
    # TODO uncomment
    # uses: atls/shared/.github/workflows/multiplatform-version.yaml@master
    uses: atls/shared/.github/workflows/multiplatform-version.yaml@refactor/workflow
    permissions: write-all
    secrets:
      appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}
    with:
      appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
      reviewerUsername: iwwwanow
