name: Bump version

on:
  pull_request:
    branches-ignore:
      - "release/**"
  # TODO uncomment
  #   types:
  #     - closed
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: atls/kmp/.github/actions/version@refactor/version
        # TODO uncomment
        # - uses: atls/kmp/.github/actions/version@master
        #   if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        with:
          appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          appSecret: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
